import { z } from 'zod';

export const createCustomerSchema = z.object({
  personType: z.enum(['INDIVIDUAL', 'COMPANY']).default('INDIVIDUAL'),
  customerTypeId: z.string().optional(),
  fullName: z.string().min(3, 'Nome completo deve ter ao menos 3 caracteres.'),
  cpf: z.string().max(20).optional(),
  rg: z.string().max(20).optional(),
  cnpj: z.string().max(20).optional(),
  stateRegistration: z.string().max(30).optional(),
  phone: z.string().max(20).optional(),
  mobilePhone: z.string().max(20).optional(),
  email: z.string().email().optional(),
  address: z.string().max(255).optional(),
  addressNumber: z.string().max(20).optional(),
  district: z.string().max(120).optional(),
  zipCode: z.string().max(20).optional(),
  city: z.string().max(120).optional(),
  state: z.string().max(120).optional(),
  birthDate: z.string().datetime().optional(),
  spcDate: z.string().datetime().optional(),
  isBlocked: z.boolean().default(false),
  hasSubscription: z.boolean().default(false),
  classification: z.enum(['GOOD', 'MEDIUM', 'BAD']).default('GOOD'),
  sellerId: z.string().optional(),
  status: z.enum(['ACTIVE', 'INACTIVE']).default('ACTIVE'),
  isSupplier: z.boolean().default(false),
  insuranceOnly: z.boolean().default(false),
  insurance: z.string().max(120).optional(),
  notes: z.string().max(1000).optional(),
});
