import { z } from 'zod';

export const createProductSchema = z.object({
  barcode: z.string().trim().max(50).optional(),
  categoryId: z.string().optional(),
  groupId: z.string().optional(),
  brand: z.string().trim().max(120).optional(),
  summary: z.string().trim().min(2, 'Resumo é obrigatório.').max(255),
  sngpc: z.string().trim().max(120).optional(),
  description: z.string().trim().min(2, 'Descrição é obrigatória.').max(255),
  rms: z.string().trim().max(50).optional(),
  presentation: z.string().trim().max(120).optional(),
  reference: z.string().trim().max(120).optional(),
  activeIngredient: z.string().trim().max(120).optional(),
  unit: z.string().trim().min(1, 'Unidade é obrigatória.').max(10),
  dcb: z.string().trim().max(120).optional(),
  packageQuantity: z.coerce.number().int().nonnegative().optional(),
  minimumQuantity: z.coerce.number().int().nonnegative().default(0),
  fractionQuantity: z.coerce.number().int().nonnegative().optional(),
  salePrice: z.coerce.number().positive('Preço de venda deve ser maior que zero.'),
  costPrice: z.coerce.number().nonnegative().optional(),
  stockQuantity: z.coerce.number().int().nonnegative().default(0),
  isGeneric: z.boolean().default(false),
  isControlled: z.boolean().default(false),
  isSpecial: z.boolean().default(false),
  isFractioned: z.boolean().default(false),
  isSimilar: z.boolean().default(false),
  ncmCode: z.string().trim().max(50).optional(),
  pisList: z.enum(['POSITIVA', 'NEGATIVA', 'NEUTRA']).optional(),
  origin: z.string().trim().max(120).optional(),
  icms: z.string().trim().max(50).optional(),
  saleOperation: z.string().trim().max(120).optional(),
  observation: z.string().trim().max(2000).optional(),
});
